# Generated by Django 5.0.1 on 2024-02-05 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_employeedetails_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='image',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to='images'),
        ),
    ]
