# Generated by Django 5.0.1 on 2024-02-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_employeedetails_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='image',
            field=models.ImageField(blank=True, default='images/default.jpg', null=True, upload_to='images'),
        ),
    ]
