# Generated by Django 5.0.1 on 2024-02-08 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_employeedetails_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], max_length=50),
        ),
        migrations.AlterField(
            model_name='employeedetails',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=100),
        ),
    ]
