# Generated by Django 5.0.1 on 2024-02-08 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_employeedetails_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetails',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='Male', max_length=50),
        ),
    ]
